services:
  - type: web
    name: novye-tehnologii
    runtime: static
    rootDir: web
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_NV_BOT_API_URL
        value: https://nvbot.artixxx.site
      - key: VITE_NV_BOT_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
